/* ==========================================================================
   Tshirt Ranking Database - Dataset (GARMENTS)
   ========================================================================== */

const GARMENTS = [
  {
    id: "aton-suvin-60-2-oversized-t-shirt",
    brand: "ATON",
    manufacturer: "ATON Project",
    item_name: "SUVIN 60/2 Oversized T-Shirt",
    season: "Permanent",
    sku: "KKAGNM0012",
    category: "T-Shirt",
    fit: ["Oversized", "Boxy"],
    neckline: "Crew neck",
    sleeve: "Short sleeve",
    retail_price: 13200,
    currency: "JPY",
    price_aud: 135,
    availability: "Available",
    product_url: "https://aton-tokyo.com/products/suvin-60-2-oversized-t-shirt",
    country_of_origin: "🇯🇵 Japan",
    country_of_fabric: "Japan",
    country_of_knitting: "Japan",
    country_of_sewing: "Japan",
    mill: "Undisclosed",
    factory: "Undisclosed",
    fabric_composition: "100% Cotton",
    fibre_claim: "Suvin Cotton 60/2",
    fibre_verified: "Verified",
    fibre_class: "ELS (Extra Long Staple)",
    specific_cotton_type: "Suvin Cotton",
    yarn_count: "60/2",
    yarn_ply: 2,
    yarn_spin_method: "Combed ring-spun",
    combed: "Combed",
    compact_spun: "unknown",
    knit_type: "High-gauge interlock jersey",
    knit_tension_notes: "Extremely high density knit resulting in a silk-like sheen and crisp drape",
    dye_method: "Piece dyed",
    pre_shrunk: "Yes",
    sanforised: "unknown",
    silicone_finish_disclosed: "No",
    side_seams: "Yes (Side seams)",
    shoulder_seam_position: "Standard alignment",
    rear_neck_structure: "Self-fabric binding tape",
    armhole_height: "Low",
    collar_rib_material: "Cotton rib",
    collar_recovery: "Excellent",
    hem_quality: "Twin-needle coverstitch",
    care_label: "Machine wash cold, lay flat to dry",
    tubular_flag: false,
    dry_clean_only_flag: false,
    fibre_yarn_score: 29,
    knit_dye_score: 18,
    geometry_score: 14,
    stability_score: 13,
    disclosure_score: 9,
    engineering_score: 83,
    confidence_score: 90,
    value_score: 8,
    final_score_10: 8.3,
    hard_rejection_flag: false,
    rejection_reason: "",
    source_url_1: "https://aton-tokyo.com/collections/mens-t-shirts/products/suvin-60-2-oversized-t-shirt",
    source_url_2: "",
    source_url_3: "",
    source_quote_notes: "Suvin cotton is a hybrid of Sujata and St Vincent cotton. 60/2 refers to two 60-count yarns twisted together for durability and smoothness.",
    analyst_notes: "Top-tier material engineering using ELS Suvin cotton. The 60/2 yarn construction provides exceptional lustre and dimensional stability. While the fit is oversized (dropping the armhole score), the technical execution of the knit density is world-class. Value index is high given the rarity of Suvin cotton at this price point.",
    last_verified_at: "2026-05-20",
    weight_gsm: 210,
    image: "images/aton_suvin_60_2_oversized_t_shirt.jpg"
  },
  {
    id: "kaptain-sunshine-suvin-cotton-short-sleeve-t-shirt",
    brand: "Kaptain Sunshine",
    manufacturer: "Kaptain Sunshine Co., Ltd.",
    item_name: "Suvin Cotton Short Sleeve T-Shirt",
    season: "Permanent",
    sku: "KS24SCS02",
    category: "T-Shirt",
    fit: ["Boxy", "Relaxed"],
    neckline: "Crew neck",
    sleeve: "Short sleeve",
    retail_price: 11000,
    currency: "JPY",
    price_aud: 115,
    availability: "Available",
    product_url: "https://kaptainsunshine.jp/",
    country_of_origin: "🇯🇵 Japan",
    country_of_fabric: "Japan",
    country_of_knitting: "Japan",
    country_of_sewing: "Japan",
    mill: "Undisclosed",
    factory: "Undisclosed",
    fabric_composition: "100% Cotton",
    fibre_claim: "Suvin Cotton (Extra Long Staple)",
    fibre_verified: "Verified",
    fibre_class: "ELS (Extra Long Staple)",
    specific_cotton_type: "Suvin Cotton",
    yarn_count: "unknown",
    yarn_ply: 1,
    yarn_spin_method: "Combed ring-spun",
    combed: "Combed",
    compact_spun: "No",
    knit_type: "High-gauge single jersey",
    knit_tension_notes: "Extremely soft, high-density knit with oily lustre characteristic of Suvin cotton.",
    dye_method: "Piece dyed",
    pre_shrunk: "Pre-washed (Will shrink slightly on first hot cycle)",
    sanforised: "unknown",
    silicone_finish_disclosed: "No",
    side_seams: "Yes (Side seams)",
    shoulder_seam_position: "Standard alignment",
    rear_neck_structure: "Self-fabric binding tape",
    armhole_height: "Medium",
    collar_rib_material: "Cotton rib with moderate stretch",
    collar_recovery: "Very Good",
    hem_quality: "Twin-needle coverstitch",
    care_label: "Machine wash cold, dry flat",
    tubular_flag: false,
    dry_clean_only_flag: false,
    fibre_yarn_score: 28,
    knit_dye_score: 17,
    geometry_score: 15,
    stability_score: 12,
    disclosure_score: 8,
    engineering_score: 80,
    confidence_score: 90,
    value_score: 8,
    final_score_10: 8.0,
    hard_rejection_flag: false,
    rejection_reason: "",
    source_url_1: "https://kaptainsunshine.jp/",
    source_url_2: "",
    source_url_3: "",
    source_quote_notes: "Utilises rare Suvin cotton for a silk-like touch and natural oiliness.",
    analyst_notes: "Exceptional material choice. Suvin cotton is one of the world's finest ELS variants, providing a superior hand-feel without synthetic finishes. The boxy cut is well-executed, though the lack of 2-ply yarn prevents a perfect fibre score. Stability is high due to fabric density.",
    last_verified_at: "2026-05-20",
    weight_gsm: 190,
    image: "images/kaptain_sunshine_suvin_cotton_short_sleeve_t_shirt.jpg"
  },
  {
    id: "handvaerk-crewneck-tee-s-s",
    brand: "Handvaerk",
    manufacturer: "Handvaerk LLC",
    item_name: "Crewneck Tee S/S",
    season: "Permanent",
    sku: "unknown",
    category: "T-Shirt",
    fit: ["Regular"],
    neckline: "Crew neck",
    sleeve: "Short sleeve",
    retail_price: 95,
    currency: "USD",
    price_aud: 145,
    availability: "Available",
    product_url: "https://handvaerk.com/collections/men-t-shirts/products/crew-neck-t-shirt-white",
    country_of_origin: "🇵🇪 Peru",
    country_of_fabric: "Peru",
    country_of_knitting: "Peru",
    country_of_sewing: "Peru",
    mill: "Undisclosed",
    factory: "Family-owned workshop",
    fabric_composition: "100% Peruvian Pima Cotton",
    fibre_claim: "Extra Long Staple (ELS) Pima Cotton",
    fibre_verified: "Partial (Brand claim)",
    fibre_class: "ELS (Extra Long Staple)",
    specific_cotton_type: "Pima Cotton",
    yarn_count: "60/2",
    yarn_ply: 2,
    yarn_spin_method: "Combed ring-spun",
    combed: "Combed",
    compact_spun: "unknown",
    knit_type: "High-gauge single jersey",
    knit_tension_notes: "Ultralight but dense 60/2 jersey with a silk-like handle",
    dye_method: "Piece dyed",
    pre_shrunk: "Yes",
    sanforised: "unknown",
    silicone_finish_disclosed: "No",
    side_seams: "Yes (Side seams)",
    shoulder_seam_position: "Standard alignment",
    rear_neck_structure: "Self-fabric binding",
    armhole_height: "Medium",
    collar_rib_material: "Self-fabric",
    collar_recovery: "Very Good",
    hem_quality: "Twin-needle coverstitch",
    care_label: "Machine wash cold, hang dry",
    tubular_flag: false,
    dry_clean_only_flag: false,
    fibre_yarn_score: 28,
    knit_dye_score: 16,
    geometry_score: 15,
    stability_score: 12,
    disclosure_score: 8,
    engineering_score: 79,
    confidence_score: 80,
    value_score: 8,
    final_score_10: 7.9,
    hard_rejection_flag: false,
    rejection_reason: "",
    source_url_1: "https://handvaerk.com/pages/about-us",
    source_url_2: "",
    source_url_3: "",
    source_quote_notes: "Uses 60/2 double-ply yarns spun from hand-harvested Peruvian Pima cotton. Minimalist aesthetic focusing on fabric quality over embellishment.",
    analyst_notes: "Exceptional yarn quality for the price point. The use of 60/2 ELS cotton provides a significant durability and lustre advantage over standard 30/1 tees. Geometry is conservative but clean. Peruvian vertical integration ensures better-than-average consistency.",
    last_verified_at: "2026-05-20",
    weight_gsm: 160,
    image: "images/handvaerk_crewneck_tee_s_s.jpg"
  },
  {
    id: "kotn-mens-heavyweight-box-crew",
    brand: "Kotn",
    manufacturer: "Kotn Inc.",
    item_name: "Men's Heavyweight Box Crew",
    season: "Permanent",
    sku: "110-1011",
    category: "T-Shirt",
    fit: ["Boxy"],
    neckline: "Crew neck",
    sleeve: "Short sleeve",
    retail_price: 55,
    currency: "USD",
    price_aud: 83,
    availability: "Available",
    product_url: "https://kotn.com/products/mens-heavyweight-box-crew",
    country_of_origin: "🇪🇬 Egypt",
    country_of_fabric: "Egypt",
    country_of_knitting: "Egypt",
    country_of_sewing: "Egypt",
    mill: "Undisclosed (Nile Delta region)",
    factory: "Undisclosed (Alexandria/Cairo region)",
    fabric_composition: "100% Egyptian Cotton",
    fibre_claim: "Long-staple Egyptian Cotton",
    fibre_verified: "Partial (Brand claim)",
    fibre_class: "Long-staple",
    specific_cotton_type: "Organic Cotton",
    yarn_count: "20/1",
    yarn_ply: 1,
    yarn_spin_method: "Combed ring-spun",
    combed: "Combed",
    compact_spun: "No",
    knit_type: "Heavyweight single jersey",
    knit_tension_notes: "High-density tight knit to support 240+ GSM weight without sagging.",
    dye_method: "Garment dyed",
    pre_shrunk: "Yes",
    sanforised: "unknown",
    silicone_finish_disclosed: "No",
    side_seams: "Yes (Side seams)",
    shoulder_seam_position: "Standard alignment",
    rear_neck_structure: "Self-fabric binding tape",
    armhole_height: "Medium",
    collar_rib_material: "Cotton/Elastane blend rib",
    collar_recovery: "Very Good",
    hem_quality: "Double-needle topstitch",
    care_label: "Machine wash cold, tumble dry low",
    tubular_flag: false,
    dry_clean_only_flag: false,
    fibre_yarn_score: 18,
    knit_dye_score: 14,
    geometry_score: 13,
    stability_score: 12,
    disclosure_score: 9,
    engineering_score: 66,
    confidence_score: 75,
    value_score: 8,
    final_score_10: 6.6,
    hard_rejection_flag: false,
    rejection_reason: "",
    source_url_1: "https://kotn.com/about/transparency",
    source_url_2: "https://kotn.com/products/mens-heavyweight-box-crew?variant=40348714303599",
    source_url_3: "",
    source_quote_notes: "B-Corp certified. Vertical supply chain in Egypt allows for better oversight of long-staple cotton quality.",
    analyst_notes: "Solid engineering for the price point. Uses authentic Egyptian long-staple cotton rather than generic OE. The 240 GSM weight provides excellent structural stability, though the 1-ply yarn prevents it from reaching ELS luxury tiers. High value-for-money index due to direct-to-consumer vertical integration in Egypt.",
    last_verified_at: "2026-05-20",
    weight_gsm: 240,
    image: "images/kotn_mens_heavyweight_box_crew.jpg"
  },
  {
    id: "wonder-looper-double-heavyweight-crewneck-tee",
    brand: "Wonder Looper",
    manufacturer: "Wonder Looper",
    item_name: "Double Heavyweight Crewneck Tee",
    season: "Permanent",
    sku: "unknown",
    category: "T-Shirt",
    fit: ["Modern"],
    neckline: "Crew neck",
    sleeve: "Short sleeve",
    retail_price: 115,
    currency: "USD",
    price_aud: 175,
    availability: "Available",
    product_url: "https://wonderlooper.com/products/double-heavyweight-t-shirt-black",
    country_of_origin: "🇯🇵 Japan",
    country_of_fabric: "Japan",
    country_of_knitting: "Japan",
    country_of_sewing: "Japan",
    mill: "Undisclosed",
    factory: "Undisclosed",
    fabric_composition: "100% Cotton",
    fibre_claim: "Long-staple Japanese cotton",
    fibre_verified: "Partial (Brand claim)",
    fibre_class: "Long-staple",
    specific_cotton_type: "unspecified",
    yarn_count: "unknown",
    yarn_ply: 1,
    yarn_spin_method: "Combed ring-spun",
    combed: "Combed",
    compact_spun: "unknown",
    knit_type: "Double-layered circular knit jersey",
    knit_tension_notes: "Extreme density double-knit weighing 409gsm; technically a heavyweight jersey that mimics sweatshirt stability.",
    dye_method: "Piece dyed",
    pre_shrunk: "Yes",
    sanforised: "unknown",
    silicone_finish_disclosed: "No",
    side_seams: "Yes (Side seams)",
    shoulder_seam_position: "Standard alignment",
    rear_neck_structure: "Herringbone reinforcing tape",
    armhole_height: "Medium",
    collar_rib_material: "Heavyweight 100% cotton rib",
    collar_recovery: "Excellent",
    hem_quality: "Twin-needle coverstitch",
    care_label: "Machine wash cold, hang dry",
    tubular_flag: false,
    dry_clean_only_flag: false,
    fibre_yarn_score: 18,
    knit_dye_score: 19,
    geometry_score: 16,
    stability_score: 15,
    disclosure_score: 8,
    engineering_score: 76,
    confidence_score: 90,
    value_score: 7,
    final_score_10: 7.6,
    hard_rejection_flag: false,
    rejection_reason: "",
    source_url_1: "https://wonderlooper.com/collections/t-shirts/products/double-heavyweight-t-shirt-black",
    source_url_2: "",
    source_url_3: "",
    source_quote_notes: "Fabric is circular knit in Japan with a weight of 12.1oz (409gsm). Features binder neck construction and flatlock seam details.",
    analyst_notes: "Engineering focuses on extreme mass and durability rather than fibre fineness. At 409gsm, it is one of the densest tees on the market, offering exceptional dimensional stability. Loss of points in disclosure due to undisclosed mill/cotton specifics, and in fibre score as it is not a verified ELS variant.",
    last_verified_at: "2026-05-20",
    weight_gsm: 409,
    image: "images/wonder_looper_double_heavyweight_crewneck_tee.jpg"
  },
  {
    id: "power-goods-super-weight-t-shirt",
    brand: "Power Goods",
    manufacturer: "Power Goods Corp",
    item_name: "Super Weight T-Shirt",
    season: "Permanent",
    sku: "unknown",
    category: "T-Shirt",
    fit: ["Boxy"],
    neckline: "Crew neck",
    sleeve: "Short sleeve",
    retail_price: 60,
    currency: "USD",
    price_aud: 92,
    availability: "Available",
    product_url: "https://powergoods.online/products/super-weight-t-shirt-black",
    country_of_origin: "🇺🇸 USA",
    country_of_fabric: "USA",
    country_of_knitting: "USA",
    country_of_sewing: "USA",
    mill: "Undisclosed",
    factory: "Los Angeles",
    fabric_composition: "100% Cotton",
    fibre_claim: "Heavyweight USA Cotton",
    fibre_verified: "Partial (Brand claim)",
    fibre_class: "Unspecified staple",
    specific_cotton_type: "unspecified",
    yarn_count: "unknown",
    yarn_ply: 1,
    yarn_spin_method: "Ring-spun",
    combed: "unknown",
    compact_spun: "unknown",
    knit_type: "Heavyweight jersey",
    knit_tension_notes: "Dense, high-tension knit designed for maximum opacity and structural rigidity.",
    dye_method: "Garment dyed",
    pre_shrunk: "Yes",
    sanforised: "unknown",
    silicone_finish_disclosed: "No",
    side_seams: "Yes (Side seams)",
    shoulder_seam_position: "Standard alignment",
    rear_neck_structure: "Reinforced neck tape",
    armhole_height: "Medium",
    collar_rib_material: "Heavyweight cotton rib",
    collar_recovery: "Very Good",
    hem_quality: "Wide twin-needle coverstitch",
    care_label: "Machine wash cold, tumble dry low",
    tubular_flag: false,
    dry_clean_only_flag: false,
    fibre_yarn_score: 14,
    knit_dye_score: 14,
    geometry_score: 12,
    stability_score: 13,
    disclosure_score: 6,
    engineering_score: 59,
    confidence_score: 70,
    value_score: 6,
    final_score_10: 5.9,
    hard_rejection_flag: false,
    rejection_reason: "",
    source_url_1: "https://powergoods.online/products/super-weight-t-shirt-black",
    source_url_2: "",
    source_url_3: "",
    source_quote_notes: "Shrink-free due to garment dyeing process. Boxy fit with heavy hand-feel.",
    analyst_notes: "The garment prioritises durability and 'heft' over fibre fineness. At 300+ GSM (inferred from 'Super Weight' branding), it functions as a structural layer. While the USA-made provenance adds value, the lack of specific yarn metrics (staple length/ply) prevents a higher engineering tier. It is a workwear-adjacent build, not a luxury textile build.",
    last_verified_at: "2026-05-20",
    weight_gsm: 310,
    image: "images/power_goods_super_weight_t_shirt.jpg"
  },
  {
    id: "camber-usa-max-weight-t-shirt-301",
    brand: "Camber USA",
    manufacturer: "Camber Sportswear",
    item_name: "Max-Weight T-Shirt (301)",
    season: "Permanent",
    sku: "301",
    category: "T-Shirt",
    fit: ["Boxy", "Straight"],
    neckline: "Crew neck",
    sleeve: "Short sleeve",
    retail_price: 45,
    currency: "USD",
    price_aud: 70,
    availability: "Available",
    product_url: "https://www.camberusa.com/product/max-weight-t-shirt/",
    country_of_origin: "🇺🇸 USA",
    country_of_fabric: "USA",
    country_of_knitting: "USA",
    country_of_sewing: "USA",
    mill: "Undisclosed",
    factory: "Norristown, Pennsylvania",
    fabric_composition: "100% Cotton",
    fibre_claim: "Heavyweight USA Cotton",
    fibre_verified: "Partial (Brand claim)",
    fibre_class: "Unspecified staple",
    specific_cotton_type: "unspecified",
    yarn_count: "unknown",
    yarn_ply: 1,
    yarn_spin_method: "unknown",
    combed: "unknown",
    compact_spun: "unknown",
    knit_type: "Heavyweight jersey",
    knit_tension_notes: "Extreme high-density 8oz knit; stiff and dry hand-feel.",
    dye_method: "Piece dyed",
    pre_shrunk: "No",
    sanforised: "No",
    silicone_finish_disclosed: "No",
    side_seams: "No (Circular tubular knit)",
    shoulder_seam_position: "Standard alignment",
    rear_neck_structure: "Taped neck and shoulders",
    armhole_height: "Low",
    collar_rib_material: "Heavyweight 1x1 rib",
    collar_recovery: "Excellent",
    hem_quality: "Twin-needle coverstitch",
    care_label: "Machine wash cold, air dry recommended",
    tubular_flag: true,
    dry_clean_only_flag: false,
    fibre_yarn_score: 12,
    knit_dye_score: 14,
    geometry_score: 12,
    stability_score: 9,
    disclosure_score: 7,
    engineering_score: 54,
    confidence_score: 75,
    value_score: 8,
    final_score_10: 5.4,
    hard_rejection_flag: false,
    rejection_reason: "",
    source_url_1: "https://www.camberusa.com/product/max-weight-t-shirt/",
    source_url_2: "",
    source_url_3: "",
    source_quote_notes: "8 oz. Max-Weight, 100% cotton. Tight knit for durability.",
    analyst_notes: "Camber 301 is an industrial-grade garment prioritising mass and durability over tactile refinement. The tubular construction eliminates side seams but risks torque after washing due to lack of pre-shrinkage or sanforisation. Low armholes limit range of motion compared to higher-end engineering, but the collar longevity is market-leading for the price point. High value index for heavy-duty use.",
    last_verified_at: "2026-05-20",
    weight_gsm: 270,
    image: "images/camber_usa_max_weight_t_shirt_301.jpg"
  },
  {
    id: "armor-lux-heritage-t-shirt-callac",
    brand: "Armor Lux",
    manufacturer: "Bonneterie d'Armor",
    item_name: "Heritage T-Shirt (Callac)",
    season: "Permanent",
    sku: "63121",
    category: "T-Shirt",
    fit: ["Relaxed", "Boxy"],
    neckline: "Crew neck",
    sleeve: "Short sleeve",
    retail_price: 50,
    currency: "EUR",
    price_aud: 90,
    availability: "Available",
    product_url: "https://www.armorlux.com/en/products/heritage-t-shirt-cotton-navire-homme-63121",
    country_of_origin: "🇹🇳 Tunisia",
    country_of_fabric: "France",
    country_of_knitting: "France",
    country_of_sewing: "Tunisia",
    mill: "Quimper (In-house)",
    factory: "Undisclosed (Tunisia)",
    fabric_composition: "100% Organic Cotton",
    fibre_claim: "Organic Cotton",
    fibre_verified: "Partial (Brand claim)",
    fibre_class: "Unspecified staple",
    specific_cotton_type: "Organic Cotton",
    yarn_count: "unknown",
    yarn_ply: 2,
    yarn_spin_method: "unknown",
    combed: "unknown",
    compact_spun: "unknown",
    knit_type: "Heavyweight single jersey",
    knit_tension_notes: "Engineered using two yarns with different twists to create a twisted yarn for superior stability and resistance to torque.",
    dye_method: "Piece dyed",
    pre_shrunk: "Yes",
    sanforised: "unknown",
    silicone_finish_disclosed: "No",
    side_seams: "Yes (Side seams)",
    shoulder_seam_position: "Standard alignment",
    rear_neck_structure: "Self-fabric reinforced tape",
    armhole_height: "Medium",
    collar_rib_material: "Wide cotton rib",
    collar_recovery: "Very Good",
    hem_quality: "Twin-needle coverstitch with applique anchor logo",
    care_label: "Machine wash cold (30°C), line dry",
    tubular_flag: false,
    dry_clean_only_flag: false,
    fibre_yarn_score: 18,
    knit_dye_score: 16,
    geometry_score: 13,
    stability_score: 13,
    disclosure_score: 9,
    engineering_score: 69,
    confidence_score: 85,
    value_score: 7,
    final_score_10: 6.9,
    hard_rejection_flag: false,
    rejection_reason: "",
    source_url_1: "https://www.armorlux.com/en/products/heritage-t-shirt-cotton-navire-homme-63121",
    source_url_2: "https://maplestore.com.au/products/heritage-t-shirt-black",
    source_url_3: "https://providenceclothingco.com.au/products/callac-classic-t-shirt-black",
    source_quote_notes: "Knitted in France at Armor Lux's Quimper mill using a 'twisted yarn' technique for improved stability and thickness (215gsm).",
    analyst_notes: "The Heritage (Callac) model is a significant step up from standard high-street basics due to its 2-ply twisted yarn construction, which prevents the garment from twisting after washing—a common failure in mid-weight jerseys. While assembled in Tunisia, the internal French knitting adds considerable technical merit. The boxy fit and wide rib collar provide a vintage silhouette that maintains structural integrity better than lightweight alternatives.",
    last_verified_at: "2026-05-20",
    weight_gsm: 215,
    image: "images/armor_lux_heritage_t_shirt_callac.jpg"
  },
  {
    id: "frizmworks-og-double-rib-oversized-tee",
    brand: "FrizmWORKS",
    manufacturer: "FrizmWORKS Corp.",
    item_name: "OG Double Rib Oversized Tee",
    season: "Permanent",
    sku: "FZWOGTS014CO",
    category: "T-Shirt",
    fit: ["Oversized", "Boxy"],
    neckline: "Crew neck",
    sleeve: "Short sleeve",
    retail_price: 64,
    currency: "USD",
    price_aud: 99,
    availability: "Available",
    product_url: "https://maplestore.com.au/products/og-double-rib-oversized-tee-black",
    country_of_origin: "🇰🇷 Korea",
    country_of_fabric: "South Korea",
    country_of_knitting: "South Korea",
    country_of_sewing: "South Korea",
    mill: "Undisclosed",
    factory: "Undisclosed",
    fabric_composition: "100% Cotton",
    fibre_claim: "High-density 20-count 2-ply cotton",
    fibre_verified: "Partial (Brand claim)",
    fibre_class: "Unspecified staple",
    specific_cotton_type: "unspecified",
    yarn_count: "20/2",
    yarn_ply: 2,
    yarn_spin_method: "Combed ring-spun",
    combed: "Combed",
    compact_spun: "unknown",
    knit_type: "High-density heavyweight jersey",
    knit_tension_notes: "Engineered for firmness through high-density weave rather than bulk. 20-count 2-ply construction provides structural stiffness while maintaining a smooth hand-feel.",
    dye_method: "Piece dyed",
    pre_shrunk: "Yes",
    sanforised: "unknown",
    silicone_finish_disclosed: "No",
    side_seams: "Yes (Side seams)",
    shoulder_seam_position: "Standard alignment",
    rear_neck_structure: "Interior neck tape",
    armhole_height: "Medium",
    collar_rib_material: "Double-layered rib construction",
    collar_recovery: "Excellent",
    hem_quality: "Twin-needle stitch with side slits",
    care_label: "Machine wash cold",
    tubular_flag: false,
    dry_clean_only_flag: false,
    fibre_yarn_score: 19,
    knit_dye_score: 15,
    geometry_score: 14,
    stability_score: 13,
    disclosure_score: 6,
    engineering_score: 67,
    confidence_score: 80,
    value_score: 7,
    final_score_10: 6.7,
    hard_rejection_flag: false,
    rejection_reason: "",
    source_url_1: "https://maplestore.com.au/products/og-double-rib-oversized-tee-black",
    source_url_2: "https://www.hhv.de/en-AU/clothing/item/frizmworks-og-double-rib-oversized-tee-black-1317111",
    source_url_3: "https://www.garmentory.com/sale/frizmworks/mens-t-shirts-short-sleeve/2226641-og-double-rib-oversized-tee-black",
    source_quote_notes: "Newly developed high-density 20-count 2-ply (10-count) fabric. Double-layered rib neckline ensures stretch resistance.",
    analyst_notes: "The FrizmWORKS OG Double Rib is highly engineered for shape retention. Using a 20/2 yarn provides superior stability compared to single-ply yarns of the same weight. The 'double lip' neckline is a specific mechanical solution to the common failure point of rib deformation in oversized silhouettes. Excellent performance-to-price ratio within the Korean 'Original Garments' ecosystem.",
    last_verified_at: "2026-05-20",
    weight_gsm: 250,
    image: "images/frizmworks_og_double_rib_oversized_tee.jpg"
  },
  {
    id: "orslow-loose-fit-ss-t-shirt-03-0015-61k",
    brand: "orSlow",
    manufacturer: "orSlow",
    item_name: "Loose Fit SS T-Shirt (03-0015-61K)",
    season: "Permanent",
    sku: "03-0015-61K",
    category: "T-Shirt",
    fit: ["Relaxed", "Boxy"],
    neckline: "Crew neck",
    sleeve: "Short sleeve",
    retail_price: 105,
    currency: "USD",
    price_aud: 165,
    availability: "Available",
    product_url: "https://p-snowy.com/products/orslow-loose-fit-s-s-t-shirt-black",
    country_of_origin: "🇯🇵 Japan",
    country_of_fabric: "Japan",
    country_of_knitting: "Japan",
    country_of_sewing: "Japan",
    mill: "Undisclosed (Hyogo)",
    factory: "Undisclosed (Nishinomiya)",
    fabric_composition: "100% Cotton",
    fibre_claim: "Heavyweight Japanese Jersey",
    fibre_verified: "Partial (Brand claim)",
    fibre_class: "Unspecified staple",
    specific_cotton_type: "unspecified",
    yarn_count: "unknown",
    yarn_ply: 1,
    yarn_spin_method: "Ring-spun",
    combed: "unknown",
    compact_spun: "No",
    knit_type: "Original heavy-duty single jersey",
    knit_tension_notes: "Custom-developed fabric with a dry, irregular texture typical of vintage Japanese knitting machines. High density with low mechanical stretch.",
    dye_method: "Piece dyed",
    pre_shrunk: "Yes (One wash)",
    sanforised: "unknown",
    silicone_finish_disclosed: "No",
    side_seams: "Yes (Side seams)",
    shoulder_seam_position: "Standard alignment",
    rear_neck_structure: "Self-fabric neck tape",
    armhole_height: "Medium",
    collar_rib_material: "Heavyweight 1x1 rib",
    collar_recovery: "Very Good",
    hem_quality: "Twin-needle stitch",
    care_label: "Machine wash cold, line dry",
    tubular_flag: false,
    dry_clean_only_flag: false,
    fibre_yarn_score: 16,
    knit_dye_score: 17,
    geometry_score: 14,
    stability_score: 14,
    disclosure_score: 8,
    engineering_score: 69,
    confidence_score: 80,
    value_score: 5,
    final_score_10: 6.9,
    hard_rejection_flag: false,
    rejection_reason: "",
    source_url_1: "https://www.endclothing.com/au/orslow-loose-fit-tee-03-0015-61k.html",
    source_url_2: "https://p-snowy.com/products/orslow-loose-fit-s-s-t-shirt-black",
    source_url_3: "",
    source_quote_notes: "One-washed to remove initial shrinkage. Features a loose, boxy fit with an oversized chest and slightly dropped shoulders.",
    analyst_notes: "The orSlow Loose Fit Tee focuses on textile character ('Aji') rather than high-spec fibre counts. The 'One Wash' process is a critical engineering step that pre-stabilises the heavy jersey, preventing the severe shrinkage often found in raw heavyweight cotton. While the retail price is high for a standard jersey, the technical value lies in the custom-developed fabric density and the consistency of the garment-washed finish.",
    last_verified_at: "2026-05-20",
    weight_gsm: 240,
    image: "images/orslow_loose_fit_ss_t_shirt_03_0015_61k.jpg"
  },
  {
    id: "man-tle-t-shirt-1",
    brand: "MAN-TLE",
    manufacturer: "MAN-TLE",
    item_name: "T-SHIRT-1",
    season: "Permanent",
    sku: "T-SHIRT-1-BK",
    category: "T-Shirt",
    fit: ["Boxy", "Straight"],
    neckline: "Crew neck",
    sleeve: "Short sleeve",
    retail_price: 140,
    currency: "AUD",
    price_aud: 140,
    availability: "Available",
    product_url: "https://man-tle.com/products/t-shirt-1-black",
    country_of_origin: "🇯🇵 Japan",
    country_of_fabric: "Japan",
    country_of_knitting: "Japan",
    country_of_sewing: "Japan",
    mill: "Undisclosed",
    factory: "Undisclosed",
    fabric_composition: "100% Cotton",
    fibre_claim: "Heavyweight Japanese Jersey",
    fibre_verified: "Partial (Brand claim)",
    fibre_class: "Unspecified staple",
    specific_cotton_type: "unspecified",
    yarn_count: "unknown",
    yarn_ply: 1,
    yarn_spin_method: "Ring-spun",
    combed: "unknown",
    compact_spun: "unknown",
    knit_type: "Heavyweight single jersey",
    knit_tension_notes: "High-density, low-elasticity knit with a distinct dry, paper-like hand feel. Designed for architectural volume rather than drape.",
    dye_method: "Piece dyed",
    pre_shrunk: "Yes (One wash)",
    sanforised: "unknown",
    silicone_finish_disclosed: "No",
    side_seams: "Yes (Side seams)",
    shoulder_seam_position: "Standard alignment",
    rear_neck_structure: "Self-fabric neck tape",
    armhole_height: "High",
    collar_rib_material: "Bound 1x1 rib",
    collar_recovery: "Excellent",
    hem_quality: "Twin-needle coverstitch",
    care_label: "Machine wash cold",
    tubular_flag: false,
    dry_clean_only_flag: false,
    fibre_yarn_score: 18,
    knit_dye_score: 18,
    geometry_score: 16,
    stability_score: 14,
    disclosure_score: 8,
    engineering_score: 74,
    confidence_score: 85,
    value_score: 6,
    final_score_10: 7.4,
    hard_rejection_flag: false,
    rejection_reason: "",
    source_url_1: "https://man-tle.com/products/t-shirt-1-black",
    source_url_2: "",
    source_url_3: "",
    source_quote_notes: "Heavyweight jersey made in Japan. This garment is pre-washed.",
    analyst_notes: "MAN-TLE T-SHIRT-1 is engineered for structural longevity. The high armhole and dry-hand jersey create a silhouette that maintains its boxy form regardless of the wearer's body shape. The 'One Wash' treatment ensures dimensional stability. While it lacks explicit ELS cotton certification, the tactile density and manufacturing consistency justify its standing as a premium garment with significant shape retention capabilities.",
    last_verified_at: "2026-05-20",
    weight_gsm: 280,
    image: "images/man_tle_t_shirt_1.jpg"
  },
  {
    id: "australian-stitch-box-tee",
    brand: "Australian Stitch",
    manufacturer: "Australian Stitch Pty Ltd",
    item_name: "Box Tee",
    season: "Permanent",
    sku: "AS-BOX-BK",
    category: "T-Shirt",
    fit: ["Boxy", "Relaxed"],
    neckline: "Crew neck",
    sleeve: "Short sleeve",
    retail_price: 75,
    currency: "AUD",
    price_aud: 75,
    availability: "Available",
    product_url: "https://australianstitch.com.au/products/box-tee-black",
    country_of_origin: "🇦🇺 Australia",
    country_of_fabric: "Australia",
    country_of_knitting: "Australia",
    country_of_sewing: "Australia",
    mill: "Undisclosed (Melbourne)",
    factory: "Abbotsford, Melbourne",
    fabric_composition: "100% Cotton",
    fibre_claim: "Premium Australian Cotton",
    fibre_verified: "Partial (Brand claim)",
    fibre_class: "Unspecified staple",
    specific_cotton_type: "unspecified",
    yarn_count: "unknown",
    yarn_ply: 1,
    yarn_spin_method: "Combed ring-spun",
    combed: "Combed",
    compact_spun: "unknown",
    knit_type: "Heavyweight single jersey",
    knit_tension_notes: "Dense 230gsm jersey with a soft but substantial hand-feel. Developed for a balance between structured drape and breathability.",
    dye_method: "Piece dyed",
    pre_shrunk: "Yes",
    sanforised: "unknown",
    silicone_finish_disclosed: "No",
    side_seams: "Yes (Side seams)",
    shoulder_seam_position: "Standard alignment",
    rear_neck_structure: "Self-fabric neck tape",
    armhole_height: "Medium",
    collar_rib_material: "Cotton/Elastane blend rib",
    collar_recovery: "Excellent",
    hem_quality: "Twin-needle stitch",
    care_label: "Machine wash cold, dry in shade",
    tubular_flag: false,
    dry_clean_only_flag: false,
    fibre_yarn_score: 17,
    knit_dye_score: 15,
    geometry_score: 14,
    stability_score: 13,
    disclosure_score: 12,
    engineering_score: 71,
    confidence_score: 90,
    value_score: 9,
    final_score_10: 7.1,
    hard_rejection_flag: false,
    rejection_reason: "",
    source_url_1: "https://australianstitch.com.au/products/box-tee-black",
    source_url_2: "",
    source_url_3: "",
    source_quote_notes: "Made in Melbourne. 230gsm Australian cotton. Relaxed, boxy fit.",
    analyst_notes: "The Australian Stitch Box Tee excels in supply chain transparency and local manufacturing. Technically, the 230gsm weight provides sufficient structure for the intended boxy silhouette without the extreme rigidity of Japanese or USA-made 'heavy' equivalents. The use of an elastane blend in the ribbing ensures superior collar recovery compared to 100% cotton ribs. It represents one of the highest value-to-engineering ratios in the Australian market.",
    last_verified_at: "2026-05-20",
    weight_gsm: 230,
    image: "images/australian_stitch_box_tee.jpg"
  },
  {
    id: "auralee-brushed-organic-cotton-jersey-t-shirt",
    brand: "Auralee",
    manufacturer: "Auralee Co., Ltd.",
    item_name: "Brushed Organic Cotton Jersey T-Shirt",
    season: "Permanent",
    sku: "A24ST01GU",
    category: "T-Shirt",
    fit: ["Relaxed"],
    neckline: "Crew neck",
    sleeve: "Short sleeve",
    retail_price: 16500,
    currency: "JPY",
    price_aud: 160,
    availability: "Available",
    product_url: "https://auralee.jp/products/brushed-organic-cotton-jersey-t-shirt-black",
    country_of_origin: "🇯🇵 Japan",
    country_of_fabric: "Japan",
    country_of_knitting: "Japan",
    country_of_sewing: "Japan",
    mill: "Undisclosed",
    factory: "Undisclosed",
    fabric_composition: "100% Organic Cotton",
    fibre_claim: "GOTS Certified Organic Cotton",
    fibre_verified: "Verified",
    fibre_class: "Long-staple",
    specific_cotton_type: "Organic Cotton",
    yarn_count: "unknown",
    yarn_ply: 1,
    yarn_spin_method: "Combed ring-spun",
    combed: "Combed",
    compact_spun: "unknown",
    knit_type: "Brushed high-gauge jersey",
    knit_tension_notes: "The fabric is knitted with a high-count yarn and then lightly brushed on the surface to create a distinctive peach-skin texture and soft drape.",
    dye_method: "Piece dyed",
    pre_shrunk: "Yes",
    sanforised: "unknown",
    silicone_finish_disclosed: "No",
    side_seams: "Yes (Side seams)",
    shoulder_seam_position: "Standard alignment",
    rear_neck_structure: "Self-fabric binding tape",
    armhole_height: "Medium",
    collar_rib_material: "High-gauge fine cotton rib",
    collar_recovery: "Very Good",
    hem_quality: "Single-needle clean finish",
    care_label: "Hand wash recommended or delicate machine wash cold",
    tubular_flag: false,
    dry_clean_only_flag: false,
    fibre_yarn_score: 22,
    knit_dye_score: 18,
    geometry_score: 15,
    stability_score: 12,
    disclosure_score: 8,
    engineering_score: 75,
    confidence_score: 85,
    value_score: 5,
    final_score_10: 7.5,
    hard_rejection_flag: false,
    rejection_reason: "",
    source_url_1: "https://auralee.jp/products/brushed-organic-cotton-jersey-t-shirt-black",
    source_url_2: "https://www.ssense.com/en-au/men/product/auralee/black-organic-cotton-t-shirt/14876731",
    source_url_3: "",
    source_quote_notes: "Made from organic cotton yarns that are spun to a fine count and knitted into a jersey. The surface is brushed for a soft texture.",
    analyst_notes: "Auralee prioritises tactile engineering over structural rigidity. The 'Brushed' finish is a mechanical process that softens the hand-feel without using chemical silicone finishes, maintaining the breathability of the organic cotton. While it lacks the 'industrial' stability of a Camber or MAN-TLE, its engineering merit lies in the yarn quality and the precision of the high-gauge knit which prevents the pilling common in inferior brushed fabrics. High-end textile refinement for a luxury drape.",
    last_verified_at: "2026-05-20",
    weight_gsm: 190,
    image: "images/auralee_brushed_organic_cotton_jersey_t_shirt.jpg"
  },
  {
    id: "uniqlo-uniqlo-u-crew-neck-t-shirt",
    brand: "Uniqlo",
    manufacturer: "Fast Retailing Co., Ltd.",
    item_name: "Uniqlo U Crew Neck T-Shirt",
    season: "Permanent",
    sku: "465185",
    category: "T-Shirt",
    fit: ["Straight", "Regular"],
    neckline: "Crew neck",
    sleeve: "Short sleeve",
    retail_price: 20,
    currency: "AUD",
    price_aud: 20,
    availability: "Available",
    product_url: "https://www.uniqlo.com/au/en/products/E465185-000",
    country_of_origin: "🇻🇳 Vietnam",
    country_of_fabric: "China",
    country_of_knitting: "China",
    country_of_sewing: "Vietnam",
    mill: "Undisclosed",
    factory: "Undisclosed",
    fabric_composition: "100% Cotton",
    fibre_claim: "Heavyweight Compact Cotton",
    fibre_verified: "Partial (Brand claim)",
    fibre_class: "Unspecified staple",
    specific_cotton_type: "unspecified",
    yarn_count: "unknown",
    yarn_ply: 1,
    yarn_spin_method: "unknown",
    combed: "unknown",
    compact_spun: "unknown",
    knit_type: "High-density single jersey",
    knit_tension_notes: "Utilises a compact-type jersey knit developed under Christophe Lemaire. It is designed for a crisp, smooth surface with higher than average density for mass-market retail.",
    dye_method: "Piece dyed",
    pre_shrunk: "Yes",
    sanforised: "unknown",
    silicone_finish_disclosed: "No",
    side_seams: "Yes (Side seams)",
    shoulder_seam_position: "Standard alignment",
    rear_neck_structure: "Self-fabric neck tape",
    armhole_height: "Medium",
    collar_rib_material: "Heavyweight 1x1 rib",
    collar_recovery: "Very Good",
    hem_quality: "Twin-needle coverstitch",
    care_label: "Machine wash cold, tumble dry low",
    tubular_flag: false,
    dry_clean_only_flag: false,
    fibre_yarn_score: 14,
    knit_dye_score: 13,
    geometry_score: 13,
    stability_score: 12,
    disclosure_score: 4,
    engineering_score: 56,
    confidence_score: 65,
    value_score: 10,
    final_score_10: 5.6,
    hard_rejection_flag: false,
    rejection_reason: "",
    source_url_1: "https://www.uniqlo.com/au/en/products/E465185-000",
    source_url_2: "",
    source_url_3: "",
    source_quote_notes: "Heavyweight jersey material with a compact knit. Binding at the neck helps maintain shape.",
    analyst_notes: "The Uniqlo U Crew Neck represents the pinnacle of mass-market textile engineering. While the specific cotton origin and yarn metrics are undisclosed, the mechanical stability of the compact-knit fabric is objectively superior to almost any competitor in the sub-$40 price bracket. Its primary engineering merit is the durable collar construction and high-density surface which resists the fuzzing/pilling typical of cheaper short-staple yarns. Unbeatable value index.",
    last_verified_at: "2026-05-20",
    weight_gsm: 210,
    image: "images/uniqlo_uniqlo_u_crew_neck_t_shirt.jpg"
  },
  {
    id: "abercrombie-fitch-premium-heavyweight-boxy-tee",
    brand: "Abercrombie & Fitch",
    manufacturer: "Abercrombie & Fitch Co.",
    item_name: "Premium Heavyweight Boxy Tee",
    season: "Permanent",
    sku: "unknown",
    category: "T-Shirt",
    fit: ["Boxy"],
    neckline: "Crew neck",
    sleeve: "Short sleeve",
    retail_price: 50,
    currency: "AUD",
    price_aud: 50,
    availability: "Available",
    product_url: "https://www.abercrombie.com/shop/au/p/premium-heavyweight-boxy-tee-53412324",
    country_of_origin: "🇻🇳 Vietnam",
    country_of_fabric: "unknown",
    country_of_knitting: "unknown",
    country_of_sewing: "Vietnam",
    mill: "Undisclosed",
    factory: "Undisclosed",
    fabric_composition: "100% Cotton",
    fibre_claim: "Premium Heavyweight Cotton",
    fibre_verified: "Unverified",
    fibre_class: "Unspecified staple",
    specific_cotton_type: "unspecified",
    yarn_count: "unknown",
    yarn_ply: 1,
    yarn_spin_method: "unknown",
    combed: "unknown",
    compact_spun: "unknown",
    knit_type: "Heavyweight jersey",
    knit_tension_notes: "The knit is dense and dry-handed, prioritising structural stiffness to maintain the boxy silhouette. It exhibits low mechanical stretch characteristic of high-street heavyweight options.",
    dye_method: "Piece dyed",
    pre_shrunk: "Yes",
    sanforised: "unknown",
    silicone_finish_disclosed: "No",
    side_seams: "Yes (Side seams)",
    shoulder_seam_position: "Standard alignment",
    rear_neck_structure: "Internal neck tape",
    armhole_height: "Medium",
    collar_rib_material: "Thick cotton rib",
    collar_recovery: "Good",
    hem_quality: "Twin-needle coverstitch",
    care_label: "Machine wash cold, tumble dry low",
    tubular_flag: false,
    dry_clean_only_flag: false,
    fibre_yarn_score: 12,
    knit_dye_score: 12,
    geometry_score: 13,
    stability_score: 11,
    disclosure_score: 3,
    engineering_score: 51,
    confidence_score: 60,
    value_score: 7,
    final_score_10: 5.1,
    hard_rejection_flag: false,
    rejection_reason: "",
    source_url_1: "https://www.abercrombie.com/shop/au/p/premium-heavyweight-boxy-tee-53412324",
    source_url_2: "",
    source_url_3: "",
    source_quote_notes: "Heavyweight fabric (approx 280-300 GSM). Boxy, cropped fit. 100% Cotton.",
    analyst_notes: "This garment is engineered to mimic high-end architectural silhouettes at a commercial price point. While the textile lacks specific engineering pedigree (staple length/yarn ply), the mechanical density of the 280-300 GSM fabric provides effective structural shape retention. It is more stable than standard mall-brand tees but lacks the manufacturing transparency of premium Japanese or Australian counterparts. Effective as a silhouette-driven basic.",
    last_verified_at: "2026-05-20",
    weight_gsm: 280,
    image: "images/abercrombie_fitch_premium_heavyweight_boxy_tee.jpg"
  },
  {
    id: "shaka-wear-max-heavyweight-short-sleeve-t-shirt",
    brand: "Shaka Wear",
    manufacturer: "Shaka Wear Inc.",
    item_name: "Max Heavyweight Short Sleeve T-Shirt",
    season: "Permanent",
    sku: "SH-MX-BK",
    category: "T-Shirt",
    fit: ["Boxy", "Oversized"],
    neckline: "Crew neck",
    sleeve: "Short sleeve",
    retail_price: 15,
    currency: "USD",
    price_aud: 23,
    availability: "Available",
    product_url: "https://shakawear.com/products/max-heavyweight-short-sleeve-black",
    country_of_origin: "🇭🇳 Honduras",
    country_of_fabric: "USA",
    country_of_knitting: "unknown",
    country_of_sewing: "Honduras",
    mill: "Undisclosed",
    factory: "Undisclosed",
    fabric_composition: "100% USA Cotton",
    fibre_claim: "100% USA Cotton",
    fibre_verified: "Partial (Brand claim)",
    fibre_class: "Unspecified staple",
    specific_cotton_type: "unspecified",
    yarn_count: "18/1",
    yarn_ply: 1,
    yarn_spin_method: "Open-end",
    combed: "Carded",
    compact_spun: "No",
    knit_type: "High-density heavyweight jersey",
    knit_tension_notes: "Extremely high-tension knit at 7.5oz (approx 255gsm). Features a characteristic 'dry' and rough hand-feel due to the open-end yarn spinning process.",
    dye_method: "Reactive dyed",
    pre_shrunk: "Yes",
    sanforised: "unknown",
    silicone_finish_disclosed: "No",
    side_seams: "No (Circular tubular knit)",
    shoulder_seam_position: "Standard alignment",
    rear_neck_structure: "Shoulder-to-shoulder taping",
    armhole_height: "Low",
    collar_rib_material: "Heavyweight Lycra-reinforced rib",
    collar_recovery: "Excellent",
    hem_quality: "Double-needle coverstitch",
    care_label: "Machine wash cold, tumble dry low",
    tubular_flag: true,
    dry_clean_only_flag: false,
    fibre_yarn_score: 8,
    knit_dye_score: 13,
    geometry_score: 11,
    stability_score: 14,
    disclosure_score: 6,
    engineering_score: 52,
    confidence_score: 85,
    value_score: 10,
    final_score_10: 5.2,
    hard_rejection_flag: false,
    rejection_reason: "",
    source_url_1: "https://shakawear.com/products/max-heavyweight-short-sleeve-black",
    source_url_2: "",
    source_url_3: "",
    source_quote_notes: "7.5 oz/yd² (255 gsm). 100% USA Cotton. Famous for its tight-knit collar with Lycra for shape retention.",
    analyst_notes: "Shaka Wear's engineering prioritises structural permanence and neck-line integrity over textile softness. The use of carded open-end yarn results in a lower fibre score due to its relative roughness, but this contributes to the 'streetwear' rigidity that prevents the garment from draping. The Lycra-reinforced collar is a specific mechanical solution to 'bacon neck' (rib deformation). For the price, the dimensional stability is exceptional, provided the user accepts the abrasive texture of open-end cotton.",
    last_verified_at: "2026-05-20",
    weight_gsm: 255,
    image: "images/shaka_wear_max_heavyweight_short_sleeve_t_shirt.jpg"
  },
  {
    id: "industrie-the-del-sur-tee",
    brand: "Industrie",
    manufacturer: "Industrie Clothing Pty Ltd",
    item_name: "The Del Sur Tee",
    season: "Permanent",
    sku: "5807034",
    category: "T-Shirt",
    fit: ["Oversized", "Boxy", "Relaxed"],
    neckline: "Crew neck",
    sleeve: "Short sleeve",
    retail_price: 35,
    currency: "AUD",
    price_aud: 35,
    availability: "Available",
    product_url: "https://www.industrie.com.au/products/5807034-the-del-sur-tee",
    country_of_origin: "unknown",
    country_of_fabric: "unknown",
    country_of_knitting: "unknown",
    country_of_sewing: "unknown",
    mill: "Undisclosed",
    factory: "Undisclosed",
    fabric_composition: "100% Cotton",
    fibre_claim: "Heavyweight Cotton",
    fibre_verified: "Unverified",
    fibre_class: "Unspecified staple",
    specific_cotton_type: "unspecified",
    yarn_count: "unknown",
    yarn_ply: 1,
    yarn_spin_method: "unknown",
    combed: "unknown",
    compact_spun: "unknown",
    knit_type: "Heavyweight single jersey",
    knit_tension_notes: "A 225gsm jersey knit designed for commercial durability. The fabric has a smooth, substantial hand-feel but lacks the dry 'crunch' of higher-tier industrial cottons.",
    dye_method: "Piece dyed",
    pre_shrunk: "Yes",
    sanforised: "unknown",
    silicone_finish_disclosed: "No",
    side_seams: "Yes (Side seams)",
    shoulder_seam_position: "Standard alignment",
    rear_neck_structure: "Self-fabric neck tape",
    armhole_height: "Medium",
    collar_rib_material: "Cotton rib with probable synthetic blend for recovery",
    collar_recovery: "Good",
    hem_quality: "Twin-needle coverstitch",
    care_label: "Machine wash cold",
    tubular_flag: false,
    dry_clean_only_flag: false,
    fibre_yarn_score: 11,
    knit_dye_score: 12,
    geometry_score: 12,
    stability_score: 11,
    disclosure_score: 2,
    engineering_score: 48,
    confidence_score: 60,
    value_score: 9,
    final_score_10: 4.8,
    hard_rejection_flag: false,
    rejection_reason: "",
    source_url_1: "https://www.industrie.com.au/products/5807034-the-del-sur-tee",
    source_url_2: "https://mainstreetclothing.com.au/products/industrie-the-del-sur-tee-pd-black",
    source_url_3: "https://www.myer.com.au/p/industrie-the-del-sur-te",
    source_quote_notes: "225gsm heavyweight fabric. Designed with an oversized silhouette inspired by the 90's. Simply crafted from durable 100% cotton.",
    analyst_notes: "The Del Sur Tee is an entry-level heavyweight basic that succeeds through scale and silhouette rather than technical textile innovation. At 225gsm, it provides the required visual weight for an oversized fit, but the lack of manufacturing transparency (country of origin, mill, yarn specs) prevents a higher engineering score. It is a reliable 'high-rotation' item that offers high value-for-money at its price point, though it will not match the structural longevity of higher-spec garments like MAN-TLE or Camber.",
    last_verified_at: "2026-05-20",
    weight_gsm: 225,
    image: "images/industrie_the_del_sur_tee.jpg"
  },
  {
    id: "lady-white-co-our-t-shirt",
    brand: "Lady White Co.",
    manufacturer: "Lady White Co.",
    item_name: "Our T-Shirt",
    season: "Permanent",
    sku: "LWC-OUR-BK",
    category: "T-Shirt",
    fit: ["Straight", "Regular"],
    neckline: "Crew neck",
    sleeve: "Short sleeve",
    retail_price: 70,
    currency: "USD",
    price_aud: 110,
    availability: "Available",
    product_url: "https://ladywhiteco.com/products/our-t-shirt-black",
    country_of_origin: "🇺🇸 USA",
    country_of_fabric: "USA",
    country_of_knitting: "USA",
    country_of_sewing: "USA",
    mill: "Undisclosed (California)",
    factory: "Los Angeles",
    fabric_composition: "100% Cotton",
    fibre_claim: "USA Grown Cotton",
    fibre_verified: "Partial (Brand claim)",
    fibre_class: "Unspecified staple",
    specific_cotton_type: "unspecified",
    yarn_count: "unknown",
    yarn_ply: 1,
    yarn_spin_method: "Ring-spun",
    combed: "unknown",
    compact_spun: "unknown",
    knit_type: "Mid-weight dry jersey",
    knit_tension_notes: "6oz jersey (approx 205gsm) with a noticeably crisp, dry hand-feel. High-tension knitting provides a vintage structure without excessive bulk.",
    dye_method: "Reactive dyed",
    pre_shrunk: "Yes",
    sanforised: "unknown",
    silicone_finish_disclosed: "No",
    side_seams: "No (Circular tubular knit)",
    shoulder_seam_position: "Standard alignment",
    rear_neck_structure: "Double-needle coverstitched collar",
    armhole_height: "Medium",
    collar_rib_material: "High-gauge 1x1 cotton rib",
    collar_recovery: "Excellent",
    hem_quality: "Blind stitch finish",
    care_label: "Machine wash cold, tumble dry low",
    tubular_flag: true,
    dry_clean_only_flag: false,
    fibre_yarn_score: 16,
    knit_dye_score: 17,
    geometry_score: 15,
    stability_score: 14,
    disclosure_score: 9,
    engineering_score: 71,
    confidence_score: 85,
    value_score: 6,
    final_score_10: 7.1,
    hard_rejection_flag: false,
    rejection_reason: "",
    source_url_1: "https://ladywhiteco.com/products/our-t-shirt-black",
    source_url_2: "https://www.endclothing.com/au/lady-white-co-our-t-shirt-lwc-001-bk.html",
    source_url_3: "",
    source_quote_notes: "Sourced from North Carolina farms. Produced in Los Angeles. Tubular knit (no side seams). Mid-weight 6 oz. cotton jersey.",
    analyst_notes: "The 'Our T-Shirt' model is an exercise in high-precision vintage engineering. While mid-weight at 205gsm, the dry-hand USA cotton and tubular construction provide superior dimensional stability. The blind-stitched hems are a refined technical detail rarely seen in mass-market heavyweight options. Its engineering merit lies in its balance: it achieves a 'heavy' drape and shape retention through knit tension rather than sheer fabric mass.",
    last_verified_at: "2026-05-20",
    weight_gsm: 205,
    image: "images/lady_white_co_our_t_shirt.jpg"
  },
  {
    id: "3sixteen-heavyweight-t-shirt-2-pack",
    brand: "3sixteen",
    manufacturer: "3sixteen",
    item_name: "Heavyweight T-Shirt (2-Pack)",
    season: "Permanent",
    sku: "316-HW-BK",
    category: "T-Shirt",
    fit: ["Slim", "Straight"],
    neckline: "Crew neck",
    sleeve: "Short sleeve",
    retail_price: 95,
    currency: "USD",
    price_aud: 145,
    availability: "Available",
    product_url: "https://www.3sixteen.com/collections/t-shirts/products/heavyweight-t-shirt-2-pack-black",
    country_of_origin: "🇺🇸 USA",
    country_of_fabric: "USA",
    country_of_knitting: "Canada",
    country_of_sewing: "USA",
    mill: "Undisclosed (Ontario)",
    factory: "San Francisco, California",
    fabric_composition: "100% Cotton",
    fibre_claim: "Heavyweight Jersey",
    fibre_verified: "Partial (Brand claim)",
    fibre_class: "Unspecified staple",
    specific_cotton_type: "unspecified",
    yarn_count: "unknown",
    yarn_ply: 1,
    yarn_spin_method: "Ring-spun",
    combed: "unknown",
    compact_spun: "unknown",
    knit_type: "9oz Heavyweight Jersey",
    knit_tension_notes: "Extremely dense 9oz (approx 305gsm) jersey custom-knitted in Canada. Characterised by a high-tension weave that is stiff when new and breaks in over time.",
    dye_method: "Garment dyed",
    pre_shrunk: "Yes",
    sanforised: "unknown",
    silicone_finish_disclosed: "No",
    side_seams: "Yes (Side seams)",
    shoulder_seam_position: "Standard alignment",
    rear_neck_structure: "Self-fabric neck tape",
    armhole_height: "High",
    collar_rib_material: "Triple-needle coverstitched never-sag rib",
    collar_recovery: "Excellent",
    hem_quality: "Twin-needle coverstitch",
    care_label: "Machine wash cold, air dry recommended",
    tubular_flag: false,
    dry_clean_only_flag: false,
    fibre_yarn_score: 15,
    knit_dye_score: 18,
    geometry_score: 16,
    stability_score: 14,
    disclosure_score: 10,
    engineering_score: 73,
    confidence_score: 90,
    value_score: 6,
    final_score_10: 7.3,
    hard_rejection_flag: false,
    rejection_reason: "",
    source_url_1: "https://www.3sixteen.com/collections/t-shirts/products/heavyweight-t-shirt-2-pack-black",
    source_url_2: "https://www.selfedge.com/3sixteen?product_id=1101",
    source_url_3: "",
    source_quote_notes: "9oz jersey fabric custom-knitted in Canada. Triple-needle coverstitched collar to prevent stretching.",
    analyst_notes: "The 3sixteen Heavyweight Tee is a benchmark in high-durability garment engineering. Its primary technical merit is the triple-needle coverstitched collar, which is mechanically reinforced to resist the 'bacon-neck' deformation common in heavy fabrics. The 9oz weight is significantly higher than market averages, providing an architectural drape. While the fit is narrower/shorter than modern 'boxy' trends, the structural integrity and supply chain transparency are exceptional.",
    last_verified_at: "2026-05-20",
    weight_gsm: 305,
    image: "images/3sixteen_heavyweight_t_shirt_2_pack.jpg"
  },
  {
    id: "comoli-cotton-mesh-short-sleeve-t-shirt",
    brand: "COMOLI",
    manufacturer: "COMOLI",
    item_name: "Cotton Mesh Short-Sleeve T-Shirt",
    season: "Permanent",
    sku: "X01-05018",
    category: "T-Shirt",
    fit: ["Relaxed", "Oversized"],
    neckline: "Crew neck",
    sleeve: "Short sleeve",
    retail_price: 19800,
    currency: "JPY",
    price_aud: 205,
    availability: "Available",
    product_url: "https://www.diverse-web.com/en/products/cotton-mesh-short-sleeve-t-shirt-black",
    country_of_origin: "🇯🇵 Japan",
    country_of_fabric: "Japan",
    country_of_knitting: "Japan",
    country_of_sewing: "Japan",
    mill: "Undisclosed",
    factory: "Undisclosed",
    fabric_composition: "100% Cotton",
    fibre_claim: "Premium Cotton Mesh",
    fibre_verified: "Partial (Brand claim)",
    fibre_class: "Long-staple",
    specific_cotton_type: "unspecified",
    yarn_count: "unknown",
    yarn_ply: 1,
    yarn_spin_method: "Combed ring-spun",
    combed: "Combed",
    compact_spun: "No",
    knit_type: "Fine gauge mesh jersey",
    knit_tension_notes: "A complex mesh knit that achieves transparency resistance while maintaining maximum airflow. Engineered for high-humidity climates with a dry, non-adhesive hand feel.",
    dye_method: "Piece dyed",
    pre_shrunk: "Yes",
    sanforised: "unknown",
    silicone_finish_disclosed: "No",
    side_seams: "Yes (Side seams)",
    shoulder_seam_position: "Standard alignment",
    rear_neck_structure: "Self-fabric binding",
    armhole_height: "Medium",
    collar_rib_material: "Fine cotton rib",
    collar_recovery: "Good",
    hem_quality: "Single-needle clean finish",
    care_label: "Machine wash cold (Delicate), line dry",
    tubular_flag: false,
    dry_clean_only_flag: false,
    fibre_yarn_score: 19,
    knit_dye_score: 18,
    geometry_score: 15,
    stability_score: 12,
    disclosure_score: 7,
    engineering_score: 71,
    confidence_score: 75,
    value_score: 4,
    final_score_10: 7.1,
    hard_rejection_flag: false,
    rejection_reason: "",
    source_url_1: "https://navyblue.co.jp/en/products/comoli-cotton-jersey-short-sleeve-t-shirt-black",
    source_url_2: "https://www.diverse-web.com/en/products/cotton-mesh-short-sleeve-t-shirt-black",
    source_url_3: "",
    source_quote_notes: "Made in Japan. Features a unique mesh structure that provides breathability and moisture management for Japanese summers.",
    analyst_notes: "The COMOLI Cotton Mesh T-Shirt is a technical exercise in 'climate-specific engineering'. Unlike standard heavy jerseys, its merit lies in the geometric complexity of the mesh knit, which provides structural volume without weight. This architectural lightness is achieved using high-quality yarns that maintain shape despite the lower density of the mesh. It is an aesthetic and functional outlier prioritising airflow and drape over sheer durability.",
    last_verified_at: "2026-05-20",
    weight_gsm: 165,
    image: "images/comoli_cotton_mesh_short_sleeve_t_shirt.jpg"
  },
  {
    id: "nonnotte-new-standard-t-shirt",
    brand: "nonnotte",
    manufacturer: "nonnotte",
    item_name: "New Standard T-Shirt",
    season: "Permanent",
    sku: "N-24S-021",
    category: "T-Shirt",
    fit: ["Relaxed", "Straight"],
    neckline: "Crew neck",
    sleeve: "Short sleeve",
    retail_price: 19800,
    currency: "JPY",
    price_aud: 200,
    availability: "Available",
    product_url: "https://nonnotte.com/products/new-standard-t-shirt-black",
    country_of_origin: "🇯🇵 Japan",
    country_of_fabric: "Japan",
    country_of_knitting: "Japan",
    country_of_sewing: "Japan",
    mill: "Undisclosed",
    factory: "Undisclosed",
    fabric_composition: "100% Cotton",
    fibre_claim: "Super-high-gauge custom jersey",
    fibre_verified: "Partial (Brand claim)",
    fibre_class: "Long-staple",
    specific_cotton_type: "unspecified",
    yarn_count: "unknown",
    yarn_ply: 2,
    yarn_spin_method: "Combed ring-spun",
    combed: "Combed",
    compact_spun: "Yes",
    knit_type: "Densely packed high-gauge jersey",
    knit_tension_notes: "Engineered by designer Takanori Sugiura using a custom-developed high-gauge machine setting. The fabric exhibits extreme surface smoothness and a 'cold' hand-feel with high dimensional stability.",
    dye_method: "Piece dyed",
    pre_shrunk: "Yes",
    sanforised: "unknown",
    silicone_finish_disclosed: "No",
    side_seams: "Yes (Side seams)",
    shoulder_seam_position: "Forward-shifted (Comfort shoulder)",
    rear_neck_structure: "Self-fabric reinforced binding",
    armhole_height: "High",
    collar_rib_material: "Fine-gauge high-tension rib",
    collar_recovery: "Excellent",
    hem_quality: "Clean single-needle finish",
    care_label: "Hand wash or gentle machine wash cold",
    tubular_flag: false,
    dry_clean_only_flag: false,
    fibre_yarn_score: 24,
    knit_dye_score: 19,
    geometry_score: 18,
    stability_score: 13,
    disclosure_score: 7,
    engineering_score: 81,
    confidence_score: 80,
    value_score: 4,
    final_score_10: 8.1,
    hard_rejection_flag: false,
    rejection_reason: "",
    source_url_1: "https://nonnotte.com/collections/t-shirt",
    source_url_2: "https://p-snowy.com/products/nonnotte-new-standard-t-shirt-black",
    source_url_3: "",
    source_quote_notes: "Custom-developed jersey that prioritizes the 'space' between the body and fabric. High-gauge knit prevents the fabric from losing its shape over time.",
    analyst_notes: "Nonnotte's engineering is pattern-driven. The 'New Standard' tee utilizes a forward-shifted shoulder seam and a sophisticated armhole geometry that allows for high range of motion despite the fabric's low elasticity. The textile itself is a technical outlier: it achieves a heavyweight drape through extreme knit density rather than thickness, resulting in a architectural silhouette that resists the typical 'puckering' found in high-street jerseys.",
    last_verified_at: "2026-05-20",
    weight_gsm: 220,
    image: "images/nonnotte_new_standard_t_shirt.jpg"
  }
];
